name: Test Workflow

on:
  pull_request:
    branches: '*'
  push:
    branches: '*'

env:
  NODE_DEBUG: http

jobs:
  test:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - name: "Clone project repository"
        uses: actions/checkout@v3
      - name: "Dump environment"
        run: env
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump vars context
        run: echo '${{ toJSON(vars) }}'
      - name: Dump secrets context
        run: echo '${{ toJSON(secrets) }}'
      - name: Run test script
        run: ./scripts/run-test.sh

